### ISSUE TITLE
Error if datadir is not set in hiera.yaml

### ISSUE THREAD

**Issue by rwaffen** [betadots/hdm#108]
is datadir is not set in hiera.yaml, one gets an error in the intrface about datadir being empty/nil.

datadir is not mandatory in hiera.yaml, if not set, it is assumed to be "data".

**Comment by oneiros** [comment]
Do you still have the exact error message including the stack trace? And the `hiera.yaml` you used?

Because this is actually the only place we use code from hiera itself - to get the defaults: https://github.com/betadots/hdm/blob/f54beeb8a83ecf3d3e6b2e74147d6f3fe7349c74/app/models/hiera_data/config.rb#L15

And this does in fact include the default for `datadir`:

```
> Puppet::Pops::Lookup::HieraConfigV5::DEFAULT_CONFIG_HASH
=> {"version"=>5, "defaults"=>{"datadir"=>"data", "data_hash"=>"yaml_data"}, "hierarchy"=>[{"name"=>"Common", "path"=>"common.yaml"}]}
```

So in theory this _should_ work. Also in the test data, there is a `no_config` environment without any custom `hiera.yaml` at all, that works fine.

So I suspect there is some other factor at play here. Could it be that your `hiera.yaml` _does_ include a `datadir:` setting, but without a value?

**Comment by tuxmea** [comment]
Cross check how hiera.yaml file looks at the customer.

**Comment by rwaffen** [comment]
when datadir is missing in the hiera.yaml the following is in the hdm log

```
I, [2023-02-09T14:00:48.689078 #24]  INFO -- : [c3985231-dbeb-4516-b3fd-0dcfe2b1e729] Started GET "/environments/production/nodes/puppet.test.priv.rw.betadots.training/keys" for x.x.x.x at 2023-02-09 14:00:48 +0100
I, [2023-02-09T14:00:48.690671 #24]  INFO -- : [c3985231-dbeb-4516-b3fd-0dcfe2b1e729] Processing by KeysController#index as HTML
I, [2023-02-09T14:00:48.690755 #24]  INFO -- : [c3985231-dbeb-4516-b3fd-0dcfe2b1e729]   Parameters: {"environment_id"=>"production", "node_id"=>"puppet.test.priv.rw.betadots.training"}
I, [2023-02-09T14:00:48.816461 #24]  INFO -- : [c3985231-dbeb-4516-b3fd-0dcfe2b1e729] Completed 500 Internal Server Error in 126ms (ActiveRecord: 1.2ms | Allocations: 19599)
F, [2023-02-09T14:00:48.818372 #24] FATAL -- : [c3985231-dbeb-4516-b3fd-0dcfe2b1e729]
[c3985231-dbeb-4516-b3fd-0dcfe2b1e729] TypeError (no implicit conversion of nil into String):
[c3985231-dbeb-4516-b3fd-0dcfe2b1e729]
[c3985231-dbeb-4516-b3fd-0dcfe2b1e729] app/models/hiera_data/hierarchy.rb:35:in `initialize'
[c3985231-dbeb-4516-b3fd-0dcfe2b1e729] app/models/hiera_data/hierarchy.rb:35:in `new'
[c3985231-dbeb-4516-b3fd-0dcfe2b1e729] app/models/hiera_data/hierarchy.rb:35:in `datadir'
[c3985231-dbeb-4516-b3fd-0dcfe2b1e729] app/models/hiera_data.rb:18:in `block (2 levels) in all_keys'
[c3985231-dbeb-4516-b3fd-0dcfe2b1e729] app/models/hiera_data.rb:17:in `each'
[c3985231-dbeb-4516-b3fd-0dcfe2b1e729] app/models/hiera_data.rb:17:in `block in all_keys'
[c3985231-dbeb-4516-b3fd-0dcfe2b1e729] app/models/hiera_data.rb:16:in `each'
[c3985231-dbeb-4516-b3fd-0dcfe2b1e729] app/models/hiera_data.rb:16:in `all_keys'
[c3985231-dbeb-4516-b3fd-0dcfe2b1e729] app/models/key.rb:9:in `all_for'
[c3985231-dbeb-4516-b3fd-0dcfe2b1e729] app/controllers/keys_controller.rb:10:in `index'
```

**Comment by oneiros** [comment]
Thank you so much for that backtrace and especially the example configuration. I could now easily reproduce this and the fix was super simple. See #141
