### ISSUE TITLE
using main in development mode raises exception "link_tree argument must be a directory"

### ISSUE THREAD

**Issue by tuxmea** [betadots/hdm#287]
```
<p style="font-family: helvetica, verdana, arial, sans-serif; font-size: 13px; line-height: 18px; color: rgb(51, 51, 51); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(250, 250, 250); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Showing<span> </span><i>/opt/hdm/app/views/page/initial_setup.html.erb</i><span> </span>where line<span> </span><b>#</b><span> </span>raised:</p><pre style="font-size: 11px; white-space: pre-wrap; color: rgb(51, 51, 51); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(250, 250, 250); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><code>link_tree argument must be a directory</code></pre><div class="source " id="frame-source-0-0" style="border: 1px solid rgb(217, 217, 217); background: rgb(236, 236, 236); max-width: 978px; color: rgb(51, 51, 51); font-family: helvetica, verdana, arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="info" style="margin: 0px; padding: 0.5em;">Extracted source (around line<span> </span><strong style="margin: 0px; padding: 0px;">#407</strong>):</div><div class="data" style="margin: 0px; padding: 0px; font-size: 10.4px; overflow: auto; background-color: rgb(255, 255, 255);">
405 406 407 408 409 410 | path           else             raise ArgumentError, "#{directive} argument must be a directory"           end         else           # The path must be relative and start with a `./`.
-- | --


</div></div><p style="font-family: helvetica, verdana, arial, sans-serif; font-size: 13px; line-height: 18px; color: rgb(51, 51, 51); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(250, 250, 250); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"></p><p style="font-family: helvetica, verdana, arial, sans-serif; font-size: 13px; line-height: 18px; color: rgb(51, 51, 51); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(250, 250, 250); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><code>Rails.root: /opt/hdm</code></p><div id="traces-0" style="color: rgb(51, 51, 51); font-family: helvetica, verdana, arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(250, 250, 250); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><a href="http://foreman.betadots.training:3000/initial_setup#" onclick="hide('Framework-Trace-0');hide('Full-Trace-0');show('Application-Trace-0');; return false;" style="color: rgb(152, 9, 5);">Application Trace</a><span> </span>|<span> </span><a href="http://foreman.betadots.training:3000/initial_setup#" onclick="hide('Application-Trace-0');hide('Full-Trace-0');show('Framework-Trace-0');; return false;" style="color: rgb(152, 9, 5);">Framework Trace</a><span> </span>|<span> </span><a href="http://foreman.betadots.training:3000/initial_setup#" onclick="hide('Application-Trace-0');hide('Framework-Trace-0');show('Full-Trace-0');; return false;" style="color: rgb(152, 9, 5);">Full Trace</a><div id="Full-Trace-0" style="display: block;"><code class="traces" style="font-size: 11px;"><a class="trace-frames trace-frames-0" data-exception-object-id="38660" data-frame-id="0" href="http://foreman.betadots.training:3000/initial_setup#" style="color: rgb(102, 102, 102); overflow-wrap: break-word;">sprockets (4.2.1) lib/sprockets/directive_processor.rb:407:in `expand_relative_dirname'</a><br><a class="trace-frames trace-frames-0" data-exception-object-id="38660" data-frame-id="1" href="http://foreman.betadots.training:3000/initial_setup#" style="color: rgb(102, 102, 102); overflow-wrap: break-word;">sprockets (4.2.1) lib/sprockets/directive_processor.rb:359:in `process_link_tree_directive'</a><br><a class="trace-frames trace-frames-0" data-exception-object-id="38660" data-frame-id="2" href="http://foreman.betadots.training:3000/initial_setup#" style="color: rgb(102, 102, 102); overflow-wrap: break-word;">sprockets (4.2.1) lib/sprockets/directive_processor.rb:189:in `block in process_directives'</a><br><a class="trace-frames trace-frames-0" data-exception-object-id="38660" data-frame-id="3" href="http://foreman.betadots.training:3000/initial_setup#" style="color: rgb(102, 102, 102); overflow-wrap: break-word;">sprockets (4.2.1) lib/sprockets/directive_processor.rb:187:in `each'</a><br><a class="trace-frames trace-frames-0" data-exception-object-id="38660" data-frame-id="4" href="http://foreman.betadots.training:3000/initial_setup#" style="color: rgb(102, 102, 102); overflow-wrap: break-word;">sprockets (4.2.1) lib/sprockets/directive_processor.rb:187:in `process_directives'</a><br><a class="trace-frames trace-frames-0" data-exception-object-id="38660" data-frame-id="5" href="http://foreman.betadots.training:3000/initial_setup#" style="color: rgb(102, 102, 102); overflow-wrap: break-word;">sprockets (4.2.1) lib/sprockets/directive_processor.rb:84:in `_call'</a><br><a class="trace-frames trace-frames-0" data-exception-object-id="38660" data-frame-id="6" href="http://foreman.betadots.training:3000/initial_setup#" style="color: rgb(102, 102, 102); overflow-wrap: break-word;">sprockets (4.2.1) lib/sprockets/directive_processor.rb:65:in `call'</a><br><a class="trace-frames trace-frames-0" data-exception-object-id="38660" data-frame-id="7" href="http://foreman.betadots.training:3000/initial_setup#" style="color: rgb(102, 102, 102); overflow-wrap: break-word;">sprockets (4.2.1) lib/sprockets/processor_utils.rb:84:in `call_processor'</a><br><a class="trace-frames trace-frames-0" data-exception-object-id="38660" data-frame-id="8" href="http://foreman.betadots.training:3000/initial_setup#" style="color: rgb(102, 102, 102); overflow-wrap: break-word;">sprockets (4.2.1) lib/sprockets/processor_utils.rb:66:in `block in call_processors'</a><br><a class="trace-frames trace-frames-0" data-exception-object-id="38660" data-frame-id="9" href="http://foreman.betadots.training:3000/initial_setup#" style="color: rgb(102, 102, 102); overflow-wrap: break-word;">sprockets (4.2.1) lib/sprockets/processor_utils.rb:65:in `reverse_each'</a><br><a class="trace-frames trace-frames-0" data-exception-object-id="38660" data-frame-id="10" href="http://foreman.betadots.training:3000/initial_setup#" style="color: rgb(102, 102, 102); overflow-wrap: break-word;">sprockets (4.2.1) lib/sprockets/processor_utils.rb:65:in `call_processors'</a><br><a class="trace-frames trace-frames-0" data-exception-object-id="38660" data-frame-id="11" href="http://foreman.betadots.training:3000/initial_setup#" style="color: rgb(102, 102, 102); overflow-wrap: break-word;">sprockets (4.2.1) lib/sprockets/loader.rb:184:in `load_from_unloaded'</a><br><a class="trace-frames trace-frames-0" data-exception-object-id="38660" data-frame-id="12" href="http://foreman.betadots.training:3000/initial_setup#" style="color: rgb(102, 102, 102); overflow-wrap: break-word;">sprockets (4.2.1) lib/sprockets/loader.rb:59:in `block in load'</a><br><a class="trace-frames trace-frames-0" data-exception-object-id="38660" data-frame-id="13" href="http://foreman.betadots.training:3000/initial_setup#" style="color: rgb(102, 102, 102); overflow-wrap: break-word;">sprockets (4.2.1) lib/sprockets/loader.rb:339:in `fetch_asset_from_dependency_cache'</a><br><a class="trace-frames trace-frames-0" data-exception-object-id="38660" data-frame-id="14" href="http://foreman.betadots.training:3000/initial_setup#" style="color: rgb(102, 102, 102); overflow-wrap: break-word;">sprockets (4.2.1) lib/sprockets/loader.rb:43:in `load'</a><br><a class="trace-frames trace-frames-0" data-exception-object-id="38660" data-frame-id="15" href="http://foreman.betadots.training:3000/initial_setup#" style="color: rgb(102, 102, 102); overflow-wrap: break-word;">sprockets (4.2.1) lib/sprockets/cached_environment.rb:44:in `block in load'</a><br><a class="trace-frames trace-frames-0" data-exception-object-id="38660" data-frame-id="16" href="http://foreman.betadots.training:3000/initial_setup#" style="color: rgb(102, 102, 102); overflow-wrap: break-word;">concurrent-ruby (1.2.3) lib/concurrent-ruby/concurrent/map.rb:207:in `block in fetch_or_store'</a><br><a class="trace-frames trace-frames-0" data-exception-object-id="38660" data-frame-id="17" href="http://foreman.betadots.training:3000/initial_setup#" style="color: rgb(102, 102, 102); overflow-wrap: break-word;">concurrent-ruby (1.2.3) lib/concurrent-ruby/concurrent/map.rb:187:in `fetch'</a><br><a class="trace-frames trace-frames-0" data-exception-object-id="38660" data-frame-id="18" href="http://foreman.betadots.training:3000/initial_setup#" style="color: rgb(102, 102, 102); overflow-wrap: break-word;">concurrent-ruby (1.2.3) lib/concurrent-ruby/concurrent/map.rb:206:in `fetch_or_store'</a><br><a class="trace-frames trace-frames-0" data-exception-object-id="38660" data-frame-id="19" href="http://foreman.betadots.training:3000/initial_setup#" style="color: rgb(102, 102, 102); overflow-wrap: break-word;">sprockets (4.2.1) lib/sprockets/cached_environment.rb:44:in `load'</a><br><a class="trace-frames trace-frames-0" data-exception-object-id="38660" data-frame-id="20" href="http://foreman.betadots.training:3000/initial_setup#" style="color: rgb(102, 102, 102); overflow-wrap: break-word;">sprockets (4.2.1) lib/sprockets/bundle.rb:27:in `call'</a><br><a class="trace-frames trace-frames-0" data-exception-object-id="38660" data-frame-id="21" href="http://foreman.betadots.training:3000/initial_setup#" style="color: rgb(102, 102, 102); overflow-wrap: break-word;">sprockets (4.2.1) lib/sprockets/processor_utils.rb:84:in `call_processor'</a><br><a class="trace-frames trace-frames-0" data-exception-object-id="38660" data-frame-id="22" href="http://foreman.betadots.training:3000/initial_setup#" style="color: rgb(102, 102, 102); overflow-wrap: break-word;">sprockets (4.2.1) lib/sprockets/processor_utils.rb:66:in `block in call_processors'</a><br><a class="trace-frames trace-frames-0" data-exception-object-id="38660" data-frame-id="23" href="http://foreman.betadots.training:3000/initial_setup#" style="color: rgb(102, 102, 102); overflow-wrap: break-word;">sprockets (4.2.1) lib/sprockets/processor_utils.rb:65:in `reverse_each'</a><br><a class="trace-frames trace-frames-0" data-exception-object-id="38660" data-frame-id="24" href="http://foreman.betadots.training:3000/initial_setup#" style="color: rgb(102, 102, 102); overflow-wrap: break-word;">sprockets (4.2.1) lib/sprockets/processor_utils.rb:65:in `call_processors'</a><br><a class="trace-frames trace-frames-0" data-exception-object-id="38660" data-frame-id="25" href="http://foreman.betadots.training:3000/initial_setup#" style="color: rgb(102, 102, 102); overflow-wrap: break-word;">sprockets (4.2.1) lib/sprockets/loader.rb:184:in `load_from_unloaded'</a><br><a class="trace-frames trace-frames-0" data-exception-object-id="38660" data-frame-id="26" href="http://foreman.betadots.training:3000/initial_setup#" style="color: rgb(102, 102, 102); overflow-wrap: break-word;">sprockets (4.2.1) lib/sprockets/loader.rb:59:in `block in load'</a><br><a class="trace-frames trace-frames-0" data-exception-object-id="38660" data-frame-id="27" href="http://foreman.betadots.training:3000/initial_setup#" style="color: rgb(102, 102, 102); overflow-wrap: break-word;">sprockets (4.2.1) lib/sprockets/loader.rb:339:in `fetch_asset_from_dependency_cache'</a><br><a class="trace-frames trace-frames-0" data-exception-object-id="38660" data-frame-id="28" href="http://foreman.betadots.training:3000/initial_setup#" style="color: rgb(102, 102, 102); overflow-wrap: break-word;">sprockets (4.2.1) lib/sprockets/loader.rb:43:in `load'</a><br><a class="trace-frames trace-frames-0" data-exception-object-id="38660" data-frame-id="29" href="http://foreman.betadots.training:3000/initial_setup#" style="color: rgb(102, 102, 102); overflow-wrap: break-word;">sprockets (4.2.1) lib/sprockets/cached_environment.rb:44:in `block in load'</a><br><a class="trace-frames trace-frames-0" data-exception-object-id="38660" data-frame-id="30" href="http://foreman.betadots.training:3000/initial_setup#" style="color: rgb(102, 102, 102); overflow-wrap: break-word;">concurrent-ruby (1.2.3) lib/concurrent-ruby/concurrent/map.rb:207:in `block in fetch_or_store'</a><br><a class="trace-frames trace-frames-0" data-exception-object-id="38660" data-frame-id="31" href="http://foreman.betadots.training:3000/initial_setup#" style="color: rgb(102, 102, 102); overflow-wrap: break-word;">concurrent-ruby (1.2.3) lib/concurrent-ruby/concurrent/map.rb:187:in `fetch'</a><br><a class="trace-frames trace-frames-0" data-exception-object-id="38660" data-frame-id="32" href="http://foreman.betadots.training:3000/initial_setup#" style="color: rgb(102, 102, 102); overflow-wrap: break-word;">concurrent-ruby (1.2.3) lib/concurrent-ruby/concurrent/map.rb:206:in `fetch_or_store'</a><br><a class="trace-frames trace-frames-0" data-exception-object-id="38660" data-frame-id="33" href="http://foreman.betadots.training:3000/initial_setup#" style="color: rgb(102, 102, 102); overflow-wrap: break-word;">sprockets (4.2.1) lib/sprockets/cached_environment.rb:44:in `load'</a><br><a class="trace-frames trace-frames-0" data-exception-object-id="38660" data-frame-id="34" href="http://foreman.betadots.training:3000/initial_setup#" style="color: rgb(102, 102, 102); overflow-wrap: break-word;">sprockets (4.2.1) lib/sprockets/base.rb:81:in `find_asset'</a><br><a class="trace-frames trace-frames-0" data-exception-object-id="38660" data-frame-id="35" href="http://foreman.betadots.training:3000/initial_setup#" style="color: rgb(102, 102, 102); overflow-wrap: break-word;">sprockets (4.2.1) lib/sprockets/base.rb:88:in `find_all_linked_assets'</a><br><a class="trace-frames trace-frames-0" data-exception-object-id="38660" data-frame-id="36" href="http://foreman.betadots.training:3000/initial_setup#" style="color: rgb(102, 102, 102); overflow-wrap: break-word;">sprockets (4.2.1) lib/sprockets/manifest.rb:125:in `each'</a><br><a class="trace-frames trace-frames-0" data-exception-object-id="38660" data-frame-id="37" href="http://foreman.betadots.training:3000/initial_setup#" style="color: rgb(102, 102, 102); overflow-wrap: break-word;">sprockets (4.2.1) lib/sprockets/manifest.rb:125:in `to_a'</a><br><a class="trace-frames trace-frames-0" data-exception-object-id="38660" data-frame-id="38" href="http://foreman.betadots.training:3000/initial_setup#" style="color: rgb(102, 102, 102); overflow-wrap: break-word;">sprockets (4.2.1) lib/sprockets/manifest.rb:125:in `block (2 levels) in find'</a><br><a class="trace-frames trace-frames-0" data-exception-object-id="38660" data-frame-id="39" href="http://foreman.betadots.training:3000/initial_setup#" style="color: rgb(102, 102, 102); overflow-wrap: break-word;">concurrent-ruby (1.2.3) lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:24:in `block in execute'</a><br><a class="trace-frames trace-frames-0" data-exception-object-id="38660" data-frame-id="40" href="http://foreman.betadots.training:3000/initial_setup#" style="color: rgb(102, 102, 102); overflow-wrap: break-word;">concurrent-ruby (1.2.3) lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:48:in `block in synchronize'</a><br><a class="trace-frames trace-frames-0" data-exception-object-id="38660" data-frame-id="41" href="http://foreman.betadots.training:3000/initial_setup#" style="color: rgb(102, 102, 102); overflow-wrap: break-word;">concurrent-ruby (1.2.3) lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:48:in `synchronize'</a><br><a class="trace-frames trace-frames-0" data-exception-object-id="38660" data-frame-id="42" href="http://foreman.betadots.training:3000/initial_setup#" style="color: rgb(102, 102, 102); overflow-wrap: break-word;">concurrent-ruby (1.2.3) lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:48:in `synchronize'</a><br><a class="trace-frames trace-frames-0" data-exception-object-id="38660" data-frame-id="43" href="http://foreman.betadots.training:3000/initial_setup#" style="color: rgb(102, 102, 102); overflow-wrap: break-word;">concurrent-ruby (1.2.3) lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:22:in `execute'</a><br><a class="trace-frames trace-frames-0" data-exception-object-id="38660" data-frame-id="44" href="http://foreman.betadots.training:3000/initial_setup#" style="color: rgb(102, 102, 102); overflow-wrap: break-word;">concurrent-ruby (1.2.3) lib/concurrent-ruby/concurrent/promise.rb:564:in `block in realize'</a><br><a class="trace-frames trace-frames-0" data-exception-object-id="38660" data-frame-id="45" href="http://foreman.betadots.training:3000/initial_setup#" style="color: rgb(102, 102, 102); overflow-wrap: break-word;">concurrent-ruby (1.2.3) lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:359:in `run_task'</a><br><a class="trace-frames trace-frames-0" data-exception-object-id="38660" data-frame-id="46" href="http://foreman.betadots.training:3000/initial_setup#" style="color: rgb(102, 102, 102); overflow-wrap: break-word;">concurrent-ruby (1.2.3) lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:350:in `block (3 levels) in create_worker'</a><br><a class="trace-frames trace-frames-0" data-exception-object-id="38660" data-frame-id="47" href="http://foreman.betadots.training:3000/initial_setup#" style="color: rgb(102, 102, 102); overflow-wrap: break-word;">concurrent-ruby (1.2.3) lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:341:in `loop'</a><br><a class="trace-frames trace-frames-0" data-exception-object-id="38660" data-frame-id="48" href="http://foreman.betadots.training:3000/initial_setup#" style="color: rgb(102, 102, 102); overflow-wrap: break-word;">concurrent-ruby (1.2.3) lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:341:in `block (2 levels) in create_worker'</a><br><a class="trace-frames trace-frames-0" data-exception-object-id="38660" data-frame-id="49" href="http://foreman.betadots.training:3000/initial_setup#" style="color: rgb(102, 102, 102); overflow-wrap: break-word;">concurrent-ruby (1.2.3) lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:340:in `catch'</a><br><a class="trace-frames trace-frames-0" data-exception-object-id="38660" data-frame-id="50" href="http://foreman.betadots.training:3000/initial_setup#" style="color: rgb(102, 102, 102); overflow-wrap: break-word;">concurrent-ruby (1.2.3) lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:340:in `block in create_worker'</a></code></div></div>Showing /opt/hdm/app/views/page/initial_setup.html.erb where line # raised:

link_tree argument must be a directory
Extracted source (around line #407):
405
406
407
408
409
410
              
            path
          else
            raise ArgumentError, "#{directive} argument must be a directory"
          end
        else
          # The path must be relative and start with a `./`.

Rails.root: /opt/hdm

[Application Trace](http://foreman.betadots.training:3000/initial_setup#) | [Framework Trace](http://foreman.betadots.training:3000/initial_setup#) | [Full Trace](http://foreman.betadots.training:3000/initial_setup#)
[sprockets (4.2.1) lib/sprockets/directive_processor.rb:407:in `expand_relative_dirname'](http://foreman.betadots.training:3000/initial_setup#)
[sprockets (4.2.1) lib/sprockets/directive_processor.rb:359:in `process_link_tree_directive'](http://foreman.betadots.training:3000/initial_setup#)
[sprockets (4.2.1) lib/sprockets/directive_processor.rb:189:in `block in process_directives'](http://foreman.betadots.training:3000/initial_setup#)
[sprockets (4.2.1) lib/sprockets/directive_processor.rb:187:in `each'](http://foreman.betadots.training:3000/initial_setup#)
[sprockets (4.2.1) lib/sprockets/directive_processor.rb:187:in `process_directives'](http://foreman.betadots.training:3000/initial_setup#)
[sprockets (4.2.1) lib/sprockets/directive_processor.rb:84:in `_call'](http://foreman.betadots.training:3000/initial_setup#)
[sprockets (4.2.1) lib/sprockets/directive_processor.rb:65:in `call'](http://foreman.betadots.training:3000/initial_setup#)
[sprockets (4.2.1) lib/sprockets/processor_utils.rb:84:in `call_processor'](http://foreman.betadots.training:3000/initial_setup#)
[sprockets (4.2.1) lib/sprockets/processor_utils.rb:66:in `block in call_processors'](http://foreman.betadots.training:3000/initial_setup#)
[sprockets (4.2.1) lib/sprockets/processor_utils.rb:65:in `reverse_each'](http://foreman.betadots.training:3000/initial_setup#)
[sprockets (4.2.1) lib/sprockets/processor_utils.rb:65:in `call_processors'](http://foreman.betadots.training:3000/initial_setup#)
[sprockets (4.2.1) lib/sprockets/loader.rb:184:in `load_from_unloaded'](http://foreman.betadots.training:3000/initial_setup#)
[sprockets (4.2.1) lib/sprockets/loader.rb:59:in `block in load'](http://foreman.betadots.training:3000/initial_setup#)
[sprockets (4.2.1) lib/sprockets/loader.rb:339:in `fetch_asset_from_dependency_cache'](http://foreman.betadots.training:3000/initial_setup#)
[sprockets (4.2.1) lib/sprockets/loader.rb:43:in `load'](http://foreman.betadots.training:3000/initial_setup#)
[sprockets (4.2.1) lib/sprockets/cached_environment.rb:44:in `block in load'](http://foreman.betadots.training:3000/initial_setup#)
[concurrent-ruby (1.2.3) lib/concurrent-ruby/concurrent/map.rb:207:in `block in fetch_or_store'](http://foreman.betadots.training:3000/initial_setup#)
[concurrent-ruby (1.2.3) lib/concurrent-ruby/concurrent/map.rb:187:in `fetch'](http://foreman.betadots.training:3000/initial_setup#)
[concurrent-ruby (1.2.3) lib/concurrent-ruby/concurrent/map.rb:206:in `fetch_or_store'](http://foreman.betadots.training:3000/initial_setup#)
[sprockets (4.2.1) lib/sprockets/cached_environment.rb:44:in `load'](http://foreman.betadots.training:3000/initial_setup#)
[sprockets (4.2.1) lib/sprockets/bundle.rb:27:in `call'](http://foreman.betadots.training:3000/initial_setup#)
[sprockets (4.2.1) lib/sprockets/processor_utils.rb:84:in `call_processor'](http://foreman.betadots.training:3000/initial_setup#)
[sprockets (4.2.1) lib/sprockets/processor_utils.rb:66:in `block in call_processors'](http://foreman.betadots.training:3000/initial_setup#)
[sprockets (4.2.1) lib/sprockets/processor_utils.rb:65:in `reverse_each'](http://foreman.betadots.training:3000/initial_setup#)
[sprockets (4.2.1) lib/sprockets/processor_utils.rb:65:in `call_processors'](http://foreman.betadots.training:3000/initial_setup#)
[sprockets (4.2.1) lib/sprockets/loader.rb:184:in `load_from_unloaded'](http://foreman.betadots.training:3000/initial_setup#)
[sprockets (4.2.1) lib/sprockets/loader.rb:59:in `block in load'](http://foreman.betadots.training:3000/initial_setup#)
[sprockets (4.2.1) lib/sprockets/loader.rb:339:in `fetch_asset_from_dependency_cache'](http://foreman.betadots.training:3000/initial_setup#)
[sprockets (4.2.1) lib/sprockets/loader.rb:43:in `load'](http://foreman.betadots.training:3000/initial_setup#)
[sprockets (4.2.1) lib/sprockets/cached_environment.rb:44:in `block in load'](http://foreman.betadots.training:3000/initial_setup#)
[concurrent-ruby (1.2.3) lib/concurrent-ruby/concurrent/map.rb:207:in `block in fetch_or_store'](http://foreman.betadots.training:3000/initial_setup#)
[concurrent-ruby (1.2.3) lib/concurrent-ruby/concurrent/map.rb:187:in `fetch'](http://foreman.betadots.training:3000/initial_setup#)
[concurrent-ruby (1.2.3) lib/concurrent-ruby/concurrent/map.rb:206:in `fetch_or_store'](http://foreman.betadots.training:3000/initial_setup#)
[sprockets (4.2.1) lib/sprockets/cached_environment.rb:44:in `load'](http://foreman.betadots.training:3000/initial_setup#)
[sprockets (4.2.1) lib/sprockets/base.rb:81:in `find_asset'](http://foreman.betadots.training:3000/initial_setup#)
[sprockets (4.2.1) lib/sprockets/base.rb:88:in `find_all_linked_assets'](http://foreman.betadots.training:3000/initial_setup#)
[sprockets (4.2.1) lib/sprockets/manifest.rb:125:in `each'](http://foreman.betadots.training:3000/initial_setup#)
[sprockets (4.2.1) lib/sprockets/manifest.rb:125:in `to_a'](http://foreman.betadots.training:3000/initial_setup#)
[sprockets (4.2.1) lib/sprockets/manifest.rb:125:in `block (2 levels) in find'](http://foreman.betadots.training:3000/initial_setup#)
[concurrent-ruby (1.2.3) lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:24:in `block in execute'](http://foreman.betadots.training:3000/initial_setup#)
[concurrent-ruby (1.2.3) lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:48:in `block in synchronize'](http://foreman.betadots.training:3000/initial_setup#)
[concurrent-ruby (1.2.3) lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:48:in `synchronize'](http://foreman.betadots.training:3000/initial_setup#)
[concurrent-ruby (1.2.3) lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:48:in `synchronize'](http://foreman.betadots.training:3000/initial_setup#)
[concurrent-ruby (1.2.3) lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:22:in `execute'](http://foreman.betadots.training:3000/initial_setup#)
[concurrent-ruby (1.2.3) lib/concurrent-ruby/concurrent/promise.rb:564:in `block in realize'](http://foreman.betadots.training:3000/initial_setup#)
[concurrent-ruby (1.2.3) lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:359:in `run_task'](http://foreman.betadots.training:3000/initial_setup#)
[concurrent-ruby (1.2.3) lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:350:in `block (3 levels) in create_worker'](http://foreman.betadots.training:3000/initial_setup#)
[concurrent-ruby (1.2.3) lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:341:in `loop'](http://foreman.betadots.training:3000/initial_setup#)
[concurrent-ruby (1.2.3) lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:341:in `block (2 levels) in create_worker'](http://foreman.betadots.training:3000/initial_setup#)
[concurrent-ruby (1.2.3) lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:340:in `catch'](http://foreman.betadots.training:3000/initial_setup#)
[concurrent-ruby (1.2.3) lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:340:in `block in create_worker'](http://foreman.betadots.training:3000/initial_setup#)
```

**Comment by tuxmea** [comment]
Reason was missing files in local git clone:

```
git status
On branch issue-264
Your branch is up to date with 'origin/issue-264'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   Gemfile
        modified:   Gemfile.lock
        deleted:    vendor/assets/stylesheets/slimselect.scss
        deleted:    vendor/javascript/.keep
        deleted:    vendor/javascript/slim-select.js
```
