### ISSUE TITLE
HDM v2.0.0 fails upon start

### ISSUE THREAD

**Issue by tuxmea** [betadots/hdm#319]
Deployment done using container v2.0.0

Error message:

```
/usr/local/bundle/gems/zeitwerk-2.6.13/lib/zeitwerk/kernel.rb:34: warning: getoptlong was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add getoptlong to your Gemfile or gemspec. Also contact author of zeitwerk-2.6.13 to add getoptlong into its gemspec.
/usr/local/bundle/gems/zeitwerk-2.6.13/lib/zeitwerk/kernel.rb:34: warning: prime was loaded from the standard library, but is not part of the default gems since Ruby 3.1.0. Add prime to your Gemfile or gemspec. Also contact author of zeitwerk-2.6.13 to add prime into its gemspec.
/usr/local/bundle/gems/zeitwerk-2.6.13/lib/zeitwerk/kernel.rb:34: warning: syslog was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add syslog to your Gemfile or gemspec. Also contact author of zeitwerk-2.6.13 to add syslog into its gemspec.
/usr/local/bundle/gems/zeitwerk-2.6.13/lib/zeitwerk/kernel.rb:34: warning: csv was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add csv to your Gemfile or gemspec. Also contact author of zeitwerk-2.6.13 to add csv into its gemspec.
=> Booting Puma
=> Rails 7.1.3.2 application starting in production
=> Run `bin/rails server --help` for more startup options
Puma starting in single mode...
* Puma version: 6.4.2 (ruby 3.3.0-p0) ("The Eagle of Durango")
*  Min threads: 5
*  Max threads: 5
*  Environment: production
*          PID: 39
* Listening on http://0.0.0.0:3000
Use Ctrl-C to stop
I, [2024-03-05T08:58:38.033511 #39]  INFO -- : [5e4906ce-bd3d-45c6-b909-0fb109dac8be] Started GET "/" for 87.171.74.156 at 2024-03-05 08:58:38 +0100
I, [2024-03-05T08:58:38.036200 #39]  INFO -- : [5e4906ce-bd3d-45c6-b909-0fb109dac8be] Processing by PageController#index as HTML
I, [2024-03-05T08:58:38.078711 #39]  INFO -- : [5e4906ce-bd3d-45c6-b909-0fb109dac8be]   Rendered layout layouts/application.html.erb (Duration: 24.3ms | Allocations: 10084)
I, [2024-03-05T08:58:38.079110 #39]  INFO -- : [5e4906ce-bd3d-45c6-b909-0fb109dac8be] Completed 500 Internal Server Error in 43ms (ActiveRecord: 3.9ms | Allocations: 15602)
F, [2024-03-05T08:58:38.080811 #39] FATAL -- : [5e4906ce-bd3d-45c6-b909-0fb109dac8be]
[5e4906ce-bd3d-45c6-b909-0fb109dac8be] ActionView::Template::Error (undefined local variable or method `role' for an instance of User):
[5e4906ce-bd3d-45c6-b909-0fb109dac8be]     21:           get access to the puppet configuration.</p>
[5e4906ce-bd3d-45c6-b909-0fb109dac8be]     22:         <% end %>
[5e4906ce-bd3d-45c6-b909-0fb109dac8be]     23:       <% end %>
[5e4906ce-bd3d-45c6-b909-0fb109dac8be]     24:       <% if can? :index, Environment %>
[5e4906ce-bd3d-45c6-b909-0fb109dac8be]     25:         <%= link_to environments_path, class: "btn btn-primary" do %>
[5e4906ce-bd3d-45c6-b909-0fb109dac8be]     26:           <%= icon "list" %>
[5e4906ce-bd3d-45c6-b909-0fb109dac8be]     27:           Show Environments
[5e4906ce-bd3d-45c6-b909-0fb109dac8be]
[5e4906ce-bd3d-45c6-b909-0fb109dac8be] app/models/user.rb:22:in `admin?'
[5e4906ce-bd3d-45c6-b909-0fb109dac8be] app/models/ability.rb:40:in `initialize'
[5e4906ce-bd3d-45c6-b909-0fb109dac8be] app/views/page/index.html.erb:24
```

**Comment by tuxmea** [comment]
Upgrade from 1.1.0 need db:migrate
