### ISSUE TITLE
Docker Run: ExecJS::RuntimeUnavailable

### ISSUE THREAD

**Issue by rwaffen** [betadots/hdm#64]
```
hdm  | rails aborted!
hdm  | ExecJS::RuntimeUnavailable: Could not find a JavaScript runtime. See https://github.com/rails/execjs for a list of available runtimes.
hdm  | /usr/local/bundle/gems/execjs-2.8.1/lib/execjs/runtimes.rb:58:in `autodetect'
hdm  | /usr/local/bundle/gems/execjs-2.8.1/lib/execjs.rb:5:in `<module:ExecJS>'
hdm  | /usr/local/bundle/gems/execjs-2.8.1/lib/execjs.rb:4:in `<top (required)>'
hdm  | /usr/local/bundle/gems/autoprefixer-rails-10.4.7.0/lib/autoprefixer-rails/processor.rb:4:in `require'
hdm  | /usr/local/bundle/gems/autoprefixer-rails-10.4.7.0/lib/autoprefixer-rails/processor.rb:4:in `<top (required)>'
hdm  | /usr/local/bundle/gems/autoprefixer-rails-10.4.7.0/lib/autoprefixer-rails.rb:39:in `require_relative'
hdm  | /usr/local/bundle/gems/autoprefixer-rails-10.4.7.0/lib/autoprefixer-rails.rb:39:in `<top (required)>'
hdm  | /usr/local/bundle/gems/bootstrap-4.6.1/lib/bootstrap/engine.rb:3:in `require'
hdm  | /usr/local/bundle/gems/bootstrap-4.6.1/lib/bootstrap/engine.rb:3:in `<top (required)>'
hdm  | /usr/local/bundle/gems/bootstrap-4.6.1/lib/bootstrap.rb:61:in `require'
hdm  | /usr/local/bundle/gems/bootstrap-4.6.1/lib/bootstrap.rb:61:in `register_rails_engine'
hdm  | /usr/local/bundle/gems/bootstrap-4.6.1/lib/bootstrap.rb:11:in `load!'
hdm  | /usr/local/bundle/gems/bootstrap-4.6.1/lib/bootstrap.rb:75:in `<top (required)>'
hdm  | /usr/local/bundle/gems/bundler-2.3.11/lib/bundler/runtime.rb:60:in `require'
hdm  | /usr/local/bundle/gems/bundler-2.3.11/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
hdm  | /usr/local/bundle/gems/bundler-2.3.11/lib/bundler/runtime.rb:55:in `each'
hdm  | /usr/local/bundle/gems/bundler-2.3.11/lib/bundler/runtime.rb:55:in `block in require'
hdm  | /usr/local/bundle/gems/bundler-2.3.11/lib/bundler/runtime.rb:44:in `each'
hdm  | /usr/local/bundle/gems/bundler-2.3.11/lib/bundler/runtime.rb:44:in `require'
hdm  | /usr/local/bundle/gems/bundler-2.3.11/lib/bundler.rb:176:in `require'
hdm  | /hdm/config/application.rb:7:in `<top (required)>'
hdm  | /hdm/Rakefile:14:in `require_relative'
hdm  | /hdm/Rakefile:14:in `<top (required)>'
hdm  | /usr/local/bundle/gems/railties-7.0.3/lib/rails/commands/rake/rake_command.rb:20:in `block in perform'
hdm  | /usr/local/bundle/gems/railties-7.0.3/lib/rails/commands/rake/rake_command.rb:18:in `perform'
hdm  | /usr/local/bundle/gems/railties-7.0.3/lib/rails/command.rb:51:in `invoke'
hdm  | /usr/local/bundle/gems/railties-7.0.3/lib/rails/commands.rb:18:in `<top (required)>'
hdm  | bin/rails:4:in `require'
hdm  | bin/rails:4:in `<main>'
hdm  | (See full trace by running task with --trace)
…
```

i fixed this with adding 
```
gem 'mini_racer' # minimal Google V8 JS engine for execjs
```

or is it better to install nodejs into the container?

**Comment by oneiros** [comment]
Since we wanted to eliminate the dependency on node I think mini_racer is a sensible choice.
