### ISSUE TITLE
move "listen" gem  out of development group?

### ISSUE THREAD

**Issue by rwaffen** [betadots/hdm#65]
when i bundle without development, the app does not start.
but if i understand this right, from concept, development group shouldn't be necessary for a production run?

```
hdm  | rails aborted!
hdm  | LoadError: cannot load such file -- listen
hdm  | /hdm/config/environments/development.rb:75:in `block in <top (required)>'
hdm  | /hdm/config/environments/development.rb:3:in `<top (required)>'
hdm  | /hdm/config/environment.rb:5:in `<top (required)>'
hdm  | Tasks: TOP => db:create => db:load_config => environment
hdm  | (See full trace by running task with --trace)
```

to fix this, i moved the listen gem out of the development group.

**Comment by rwaffen** [comment]
ah damn, after posting, i saw that i'm in the development environment 🤦
